name: package_release

on:
  push:
    tags:
      - '*.*.*'
  pull_request:

jobs:
  test-package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py_ver:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.py_ver}}
    - name: Install Package
      run: pip install .
    - name: Test Package
      run: discordai_modelizer -V
  release:
    if: |
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags') &&
      github.repository_owner == 'A-Baji'
    needs: test-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: version
        name: Get build metadata
        run: echo "::set-output name=discordai_version::$(cat discordai/version.py | grep -oP '\d+\.\d+\.\d+')"
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.version.outputs.discordai_version}}
          release_name: Release ${{steps.version.outputs.discordai_version}}
          body: Release ${{steps.version.outputs.discordai_version}}
          draft: false
          prerelease: false